# model_source can be one of the following: local, hugging-face-cloud, or hugging-face-local
model_source: "local"

# Path to the local model file (used when model_source is "local")
model_path: "/home/jovyan/datafabric/meta-llama3.1-8b-Q8/Meta-Llama-3.1-8B-Instruct-Q8_0.gguf"