# ─────── Standard Library Imports ───────
import json  # JSON parsing and serialization
import logging  # Logging utilities
import multiprocessing  # Multi-process support for concurrency
import os  # Operating system interaction
import time  # Time-related functions
from datetime import datetime  # Date and time manipulation
from pathlib import Path  # Object-oriented filesystem paths
from typing import Any, Dict, List  # Static typing support

# ─────── Third-Party Package Imports ───────
import mlflow  # ML lifecycle platform
import mlflow.pyfunc  # MLflow support for custom Python models
from langchain.docstore.document import Document  # Core document abstraction for LangChain
from langchain_community.llms import LlamaCpp  # Local LLM interface for Llama.cpp
from langgraph.graph import StateGraph  # LangGraph for stateful agent workflows
from pydantic import BaseModel  # Data validation and model parsing

# ─────── Local Application-Specific Imports ───────
from src.agentic_workflow import build_agentic_graph  # Custom LangGraph construction logic
from src.simple_kv_memory import SimpleKVMemory  # In-memory key-value store for agent state
from src.utils import logger  # Project-wide configured logger

class AgenticModelInput(BaseModel):
    """
    Single inference request for the Audio-RAG pipeline.
    • `question`  – natural-language query from user
    • `transcript` – full transcript (already produced by Whisper) **or**
      an empty string; if empty, the LangGraph DAG will first transcribe
      the audio / video selected in the UI.
    • `file_id`   – identifier or path of the media file (used by the
      memory module to cache embeddings & answers per file).
    """
    question: str
    transcript: str | None = ""
    file_id: str

class AgenticModelOutput(BaseModel):
    """
    • `answer`   – final markdown answer generated by the LLM
    • `snippets` – the transcript segments (and timestamps) that were
      fed to the generator; useful for UI highlighting
    • `messages` – serialized intermediate LangGraph node messages
    """
    answer: str
    snippets: list[dict[str, str]]  # [{"start":"00:10","end":"00:14","text":"…"}, …]
    messages: str                   # JSON for debugging

class AgenticAudioRAGModel(mlflow.pyfunc.PythonModel):
    """
    MLflow PyFunc wrapper for the **Agentic Audio RAG** workflow.
    The underlying LangGraph DAG:
        1. (optional) Whisper-v3 transcription
        2. Chunking + vector store
        3. Retrieval + reranking
        4. Llama.cpp answer generation
        5. Memory write-back
     """

    def load_context(self, context: mlflow.pyfunc.PythonModelContext):
        """
        Load and initialize LLM and memory for use across predictions.
        """
        self.model_path: str = context.artifacts["model_path"]
        self.memory_path: str = context.artifacts["memory_path"]

        # KV-cache -> reduces latency on repeated queries for the same media
        self.memory = SimpleKVMemory(Path(self.memory_path))

        self.llm = LlamaCpp(
            model_path=self.model_path,
            n_gpu_layers=-1,
            n_batch=512,
            n_ctx=8192,
            max_tokens=1024,
            f16_kv=True,
            use_mmap=False,
            low_vram=False,
            rope_scaling=None,
            temperature=0.0,
            repeat_penalty=1.0,
            streaming=False,
            stop=None,
            seed=42,
            num_threads=multiprocessing.cpu_count(),
            verbose=False,
        )

        self.graph = build_agentic_graph()
        self.compiled_graph = self.graph.compile()


    def predict(self, context: mlflow.pyfunc.PythonModelContext, model_input: List[AgenticModelInput]
) -> List[AgenticModelOutput]:
        """
        Run the Audio-RAG agentic workflow.
        """
        results = []
        
        for row in model_input:
            transcript = row.transcript
            question = row.question
            file_id = row.file_id
        
            docs = [Document(page_content=transcript)]
        
            final_state = self.compiled_graph.invoke(
                input={
                    "question": question,
                    "docs": docs,
                    "file_id": file_id,
                    "memory": self.memory,
                    "llm": self.llm,
                    "messages": [],
                }
            )

            results.append(AgenticModelOutput(
                answer=final_state["answer"],
                snippets=final_state["snippets"],
                messages=json.dumps(final_state["messages"], indent=4),
                ))
        
        return results

    @staticmethod
    def log_model(
        model_name: str,
        model_artifacts: Dict[str, str],
    ) -> None:
        """
        Log and register the model with MLflow.
        """

        mlflow.pyfunc.log_model(
            artifact_path=model_name,
            python_model=AgenticAudioRAGModel(),
            artifacts=model_artifacts,
            registered_model_name=model_name,
            pip_requirements="../requirements.txt",
            code_paths=["../src"],
        )
